application_title: Guide on the Side
theme: GuideOnTheSide
# The timezone will default to the date.timezone PHP ini option, or UTC if it is not set.
# List of available timezones: http://php.net/manual/en/timezones.php
# timezone: UTC

database:
  datasource: Database/Mysql
  host: localhost
  login:
  password:
  database:

email:
  send_from:
  send_all_feedback_to:

google_analytics:
  enabled: false
  account_id: UA-something
  domain_name: your-domain-name.edu

piwik_analytics:
  enabled: false
  piwik_server: piwik.server.com # Your Piwik server address (no leading http:///https://)
  site_id: 99                    # Number provided by Piwik

authentication:
  # local, shibboleth, or cas
  method: local

# only fill these out if you selected shibboleth above
shibboleth:
  login_url:  https://%HOST%/Shibboleth.sso/Login
  logout_url: https://%HOST%/Shibboleth.sso/Logout
  login_link_text: Log in via Shibboleth
  username_field: Shib-uid

# To make use of CAS, set authentication.method to cas and fill in these values
# The following sample configuration would work if your CAS login url is https://cas.example.com/cas/login
# Enable force_ssl_redirect if your CAS server requires SSL.
cas:
  hostname: cas.example.com
  port: 443
  uri: cas
  force_ssl_redirect: false
